const quotes = [
    "The best way to predict your future is to create it.",
    "Believe you can and you're halfway there.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when it hurts; stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Successful people are not gifted; they just work hard, then succeed on purpose.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You don’t have to be great to start, but you have to start to be great.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "You are never too old to set another goal or to dream a new dream.",
    "If you want something you’ve never had, you must be willing to do something you’ve never done.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Don't watch the clock; do what it does. Keep going.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Opportunities don't happen. You create them.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The only place where success comes before work is in the dictionary.",
    "Believe in yourself and all that you are.",
    "The road to success and the road to failure are almost exactly the same.",
    "Act as if what you do makes a difference. It does.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "The secret of success is to be ready when your opportunity comes.",
    "The future depends on what you do today.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Do not wait to strike till the iron is hot, but make it hot by striking.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "You miss 100% of the shots you don’t take.",
    "Whether you think you can or you think you can’t, you’re right.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "The best revenge is massive success.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Success is how high you bounce when you hit bottom.",
    "Your time is limited, don't waste it living someone else's life.",
    "If you can dream it, you can do it.",
    "I find that the harder I work, the more luck I seem to have.",
    "The only way to do great work is to love what you do.",
    "Success is not in what you have, but who you are.",
    "If you’re going through hell, keep going.",
    "What we fear doing most is usually what we most need to do.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Life is what happens when you’re busy making other plans.",
    "Start where you are. Use what you have. Do what you can.",
    "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "The best way to find yourself is to lose yourself in the service of others.",
    "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.",
    "Sometimes the smallest things take up the most room in your heart.",
    "Success is not about how much money you make; it’s about the difference you make in people’s lives.",
    "Hard work beats talent when talent doesn't work hard.",
    "Dreams don’t work unless you do.",
    "Stay patient and trust your journey.",
    "You have to expect things of yourself before you can do them.",
    "The journey of a thousand miles begins with one step.",
    "Start each day with a positive thought and a grateful heart.",
    "The best way to cheer yourself up is to try to cheer somebody else up.",
    "It’s not whether you get knocked down, it’s whether you get up.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Success is the result of preparation, hard work, and learning from failure.",
    "You are enough just as you are.",
    "The only person you are destined to become is the person you decide to be.",
    "Success doesn’t come from what you do occasionally; it comes from what you do consistently.",
    "Don't limit your challenges. Challenge your limits.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "What defines us is how well we rise after falling.",
    "Life is not about finding yourself. Life is about creating yourself.",
    "Success is not about what you have, but what you give.",
    "The only limit to your impact is your imagination and commitment.",
    "You don't have to be great to start, but you have to start to be great.",
    "The best way to predict the future is to invent it.",
    "Your life is your message to the world. Make sure it’s inspiring.",
    "The only thing standing between you and your goal is the story you keep telling yourself.",
    "In the middle of every difficulty lies opportunity.",
    "You are the artist of your own life. Don't hand the paintbrush to anyone else.",
    "Your present circumstances don't determine where you can go; they merely determine where you start.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Success is the ability to go from one failure to another with no loss of enthusiasm.",
    "Don’t count the days; make the days count.",
    "Success is not just about what you accomplish in your life; it’s about what you inspire others to do.",
    "The harder the conflict, the more glorious the triumph.",
    "Doubt kills more dreams than failure ever will.",
    "Stay hungry. Stay foolish.",
    "Mistakes are proof that you are trying.",
    "Success is simply the result of making the right choices.",
    "You have the power to create your own future.",
    "The world is full of opportunities; be ready to seize them.",
    "Do not be embarrassed by your failures, learn from them and start again.",
    "Every challenge you face is an opportunity to grow.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "Your only limit is your mind.",
    "The best investment you can make is in yourself.",
    "Persistence is the twin sister of excellence.",
    "Make today so awesome that yesterday gets jealous.",
    "Set a goal so big that you can't achieve it until you grow into the person who can.",
    "Hustle until your haters ask if you’re hiring.",
    "Success is not for the lazy.",
    "A goal without a plan is just a wish.",
    "Your passion is waiting for your courage to catch up.",
    "Opportunities don't happen; you create them.",
    "When you feel like quitting, think about why you started.",
    "The future belongs to those who prepare for it today.",
    "Creativity is intelligence having fun.",
    "Stay positive, work hard, make it happen.",
    "It’s hard to beat a person who never gives up.",
    "Turn your wounds into wisdom.",
    "Success isn’t overnight. It’s when every day you get a little better than the day before.",
    "What you do today can improve all your tomorrows.",
    "Life is either a daring adventure or nothing at all.",
    "Don't wait for the perfect moment; take the moment and make it perfect.",
    "Your vibe attracts your tribe.",
    "If you can imagine it, you can achieve it.",
    "Your limitation is only your imagination.",
    "Don’t stop until you’re proud.",
    "You didn’t come this far to only come this far.",
    "The magic happens outside your comfort zone.",
    "Everything you can imagine is real.",
    "You are capable of amazing things.",
    "Don't wait for opportunity. Create it.",
    "Everything you need is already inside you.",
    "Success is a series of small wins.",
    "Keep going. Everything you need will come to you at the perfect time.",
    "The more you give away the more happy you become.",
    "The only thing worse than being blind is having sight but no vision.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; you are the author of your own story.",
    "Fall seven times, stand up eight.",
    "Opportunities multiply as they are seized.",
    "Your dreams are valid.",
    "Work hard in silence. Let success make the noise.",
    "The best revenge is to be unlike him who performed the injury.",
    "Start each day with a grateful heart.",
    "Work until your idols become your rivals.",
    "If you're going through hell, keep going.",
    "The struggle you’re in today is developing the strength you need for tomorrow.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Turn your can’ts into cans and your dreams into plans.",
    "Strive for progress, not perfection.",
    "Opportunities don't happen; you create them.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Be somebody who makes everybody feel like a somebody.",
    "Success is the byproduct of your habits.",
    "Be the change that you wish to see in the world.",
    "Work hard and be kind, and amazing things will happen.",
    "The secret of success is to be ready when your opportunity comes.",
    "Success doesn’t come from what you do occasionally; it comes from what you do consistently.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Believe in your dreams, no matter how impossible they may seem.",
    "Every day is a second chance.",
    "Life is short, and it’s up to you to make it sweet.",
    "Don’t let yesterday take up too much of today.",
    "Your best teacher is your last mistake.",
    "Work hard in silence, let success be your noise.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do what you can, with what you have, where you are.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "The mind is everything. What you think, you become.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.",
    "You are never too old to set another goal or to dream a new dream.",
    "A person who never made a mistake never tried anything new.",
    "Be yourself; everyone else is already taken.",
    "Don’t count the days, make the days count.",
    "Success is the progressive realization of a worthy goal or ideal.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.",
    "The only way to do great work is to love what you do.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Don’t be afraid to give up the good to go for the great.",
    "If you want to lift yourself up, lift up someone else.",
    "You must do the things you think you cannot do.",
    "Setting goals is the first step in turning the invisible into the visible.",
    "Your future is created by what you do today, not tomorrow.",
    "You are more powerful than you know; you are beautiful just as you are.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Do not wait to strike till the iron is hot, but make it hot by striking.",
    "The best way out is always through.",
    "Life is either a daring adventure or nothing at all.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Life is what happens when you’re busy making other plans.",
    "If you can dream it, you can do it.",
    "What we fear doing most is usually what we most need to do.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "You must do the things you think you cannot do.",
    "Life is either a daring adventure or nothing at all.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Success is how high you bounce when you hit bottom.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "Believe you can and you’re halfway there.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "Success is the result of preparation, hard work, and learning from failure.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "You don’t have to be great to start, but you have to start to be great.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "You are the artist of your own life. Don’t hand the paintbrush to anyone else.",
    "Your only limit is your mind.",
    "Life is not about waiting for the storm to pass, but about learning to dance in the rain.",
    "Success is not for the lazy.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "The only way to do great work is to love what you do.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.",
    "Success is a journey, not a destination.",
    "Don’t be afraid to give up the good to go for the great.",
    "What you do today can improve all your tomorrows.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The best way to cheer yourself up is to try to cheer somebody else up.",
    "In the middle of every difficulty lies opportunity.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "If you want something you’ve never had, you must be willing to do something you’ve never done.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "The best revenge is to be unlike him who performed the injury.",
    "You are enough just as you are.",
    "You have the power to create your own future.",
    "Success is not about what you have, but what you give.",
    "The journey of a thousand miles begins with one step.",
    "Strive for progress, not perfection.",
    "The future belongs to those who prepare for it today.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Don’t be afraid to give up the good to go for the great.",
    "Everything you can imagine is real.",
    "Don’t wait for opportunity. Create it.",
    "The only way to do great work is to love what you do.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "Believe in your dreams, no matter how impossible they may seem.",
    "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "What you do today can improve all your tomorrows.",
    "Stay positive, work hard, make it happen.",
    "Your life is your message to the world. Make sure it’s inspiring.",
    "The only limit to your impact is your imagination and commitment.",
    "The only way to do great work is to love what you do.",
    "You have the power to create your own future.",
    "You are capable of amazing things.",
    "Life is short, and it’s up to you to make it sweet.",
    "Success is not for the lazy.",
    "Work hard in silence, let success be your noise.",
    "Life is either a daring adventure or nothing at all.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "You are never too old to set another goal or to dream a new dream.",
    "Do not wait to strike till the iron is hot, but make it hot by striking.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "Don’t watch the clock; do what it does. Keep going.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Success is a series of small wins.",
    "The best revenge is massive success.",
    "Your only limit is your mind.",
    "You are the artist of your own life. Don’t hand the paintbrush to anyone else.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Don’t let yesterday take up too much of today.",
    "You are enough just as you are.",
    "If you want to lift yourself up, lift up someone else.",
    "Opportunities don't happen; you create them.",
    "You are the architect of your own destiny; you are the author of your own story.",
    "Believe you can and you’re halfway there.",
    "Don’t count the days, make the days count.",
    "Strive for progress, not perfection.",
    "Your future is created by what you do today, not tomorrow.",
    "Success is how high you bounce when you hit bottom.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Success is not for the lazy.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "What you do today can improve all your tomorrows.",
    "The best way to cheer yourself up is to try to cheer somebody else up.",
    "You must be the change you wish to see in the world.",
    "Your dreams are valid.",
    "Believe in your dreams, no matter how impossible they may seem.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "Success doesn’t come from what you do occasionally; it comes from what you do consistently.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Life is short, and it’s up to you to make it sweet.",
    "Everything you can imagine is real.",
    "The only way to do great work is to love what you do.",
    "Don’t be afraid to give up the good to go for the great.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You are the master of your destiny; you can influence, direct and control your own environment.",
    "You are never too old to set another goal or to dream a new dream.",
    "Life is not about waiting for the storm to pass, but about learning to dance in the rain.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "The mind is everything. What you think, you become.",
    "Success is not about what you have, but what you give.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Opportunities multiply as they are seized.",
    "Success is the result of preparation, hard work, and learning from failure.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Success is a journey, not a destination.",
    "Work hard and be kind, and amazing things will happen.",
    "You are enough just as you are.",
    "Believe you can and you’re halfway there.",
    "You have the power to create your own future.",
    "Your life is your message to the world. Make sure it’s inspiring.",
    "Success is not for the lazy.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "What we fear doing most is usually what we most need to do.",
    "You are capable of amazing things.",
    "Your only limit is your mind.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "You must do the things you think you cannot do.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "Don’t wait for opportunity. Create it.",
    "The best way out is always through.",
    "If you want something you’ve never had, you must be willing to do something you’ve never done.",
    "What you do today can improve all your tomorrows.",
    "Success is a series of small wins.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Don’t count the days, make the days count.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Life is what happens when you’re busy making other plans.",
    "You are more powerful than you know; you are beautiful just as you are.",
    "If you want to lift yourself up, lift up someone else.",
    "The future belongs to those who prepare for it today.",
    "You have the power to create your own future.",
    "The journey of a thousand miles begins with one step.",
    "Your dreams are valid.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Success usually comes to those who are too busy to be looking for it.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "You must be the change you wish to see in the world.",
    "Your only limit is your mind.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Believe in your dreams, no matter how impossible they may seem.",
    "Life is either a daring adventure or nothing at all.",
    "You are never too old to set another goal or to dream a new dream.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "If you want something you’ve never had, you must be willing to do something you’ve never done.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Life is not about waiting for the storm to pass, but about learning to dance in the rain.",
    "Success is a journey, not a destination.",
    "Everything you can imagine is real.",
    "The best way to cheer yourself up is to try to cheer somebody else up.",
    "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "Success is not for the lazy.",
    "You must do the things you think you cannot do.",
    "Life is either a daring adventure or nothing at all.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Believe you can and you’re halfway there.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "You are capable of amazing things.",
    "Your only limit is your mind.",
    "You are enough just as you are.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The best way out is always through.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "You are never too old to set another goal or to dream a new dream.",
    "Success is how high you bounce when you hit bottom.",
    "Your life is your message to the world. Make sure it’s inspiring.",
    "Believe in your dreams, no matter how impossible they may seem.",
    "Life is not about waiting for the storm to pass, but about learning to dance in the rain.",
    "Success is a journey, not a destination.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "What you do today can improve all your tomorrows.",
    "You have the power to create your own future.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Don’t count the days, make the days count.",
    "Success is the progressive realization of a worthy goal or ideal.",
    "Success is not for the lazy.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "Success usually comes to those who are too busy to be looking for it.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Opportunities don't happen; you create them.",
    "Your dreams are valid.",
    "You must be the change you wish to see in the world.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "If you want to lift yourself up, lift up someone else.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe you can and you’re halfway there.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "You are the artist of your own life. Don’t hand the paintbrush to anyone else.",
    "What you do today can improve all your tomorrows.",
    "You are enough just as you are.",
    "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.",
    "Life is short, and it’s up to you to make it sweet.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "Success is not for the lazy.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Life is either a daring adventure or nothing at all.",
    "You must do the things you think you cannot do.",
    "You are more powerful than you know; you are beautiful just as you are.",
    "You are the master of your destiny; you can influence, direct and control your own environment.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Your future is created by what you do today, not tomorrow.",
    "You are capable of amazing things.",
    "Believe you can and you’re halfway there.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Opportunities multiply as they are seized.",
    "Success is a journey, not a destination.",
    "Success is not about what you have, but what you give.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Your life is your message to the world. Make sure it’s inspiring.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The best way to cheer yourself up is to try to cheer somebody else up.",
    "The only way to do great work is to love what you do.",
    "Success is how high you bounce when you hit bottom.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "Success is the result of preparation, hard work, and learning from failure.",
    "Don’t let yesterday take up too much of today.",
    "Life is short, and it’s up to you to make it sweet.",
    "You must be the change you wish to see in the world.",
    "You are enough just as you are.",
    "Believe in your dreams, no matter how impossible they may seem.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "Life is either a daring adventure or nothing at all.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Success is a series of small wins.",
    "What you do today can improve all your tomorrows.",
    "You are capable of amazing things.",
    "Success is the key to happiness. Happiness is the key to success.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Life is what happens when you’re busy making other plans.",
    "You are never too old to set another goal or to dream a new dream.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "Believe you can and you’re halfway there.",
    "Your dreams are valid.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "You are more powerful than you know; you are beautiful just as you are.",
    "You are the artist of your own life. Don’t hand the paintbrush to anyone else.",
    "Everything you can imagine is real.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "The only way to do great work is to love what you do.",
    "Life is short, and it’s up to you to make it sweet.",
    "Believe in your dreams, no matter how impossible they may seem.",
    "The best way to cheer yourself up is to try to cheer somebody else up.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "Your future is created by what you do today, not tomorrow.",
    "You are enough just as you are.",
    "Success is a journey, not a destination.",
    "You have the power to create your own future.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Life is what happens when you’re busy making other plans.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "You must be the change you wish to see in the world.",
    "What you do today can improve all your tomorrows.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Success is a journey, not a destination.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Success is not for the lazy.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.",
    "Your dreams are valid.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Believe you can and you’re halfway there.",
    "Success is how high you bounce when you hit bottom.",
    "You are the master of your destiny; you can influence, direct and control your own environment.",
    "Success is a series of small wins.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "You are never too old to set another goal or to dream a new dream.",
    "Life is what happens when you’re busy making other plans.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Life is short, and it’s up to you to make it sweet.",
    "You are enough just as you are.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "You must do the things you think you cannot do.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Success is the result of preparation, hard work, and learning from failure.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe you can and you’re halfway there.",
    "You are more powerful than you know; you are beautiful just as you are.",
    "Life is either a daring adventure or nothing at all.",
    "Your life is your message to the world. Make sure it’s inspiring.",
    "Success is how high you bounce when you hit bottom.",
    "What you do today can improve all your tomorrows.",
    "Success is a journey, not a destination.",
    "Opportunities multiply as they are seized.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Believe you can and you’re halfway there.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "You are capable of amazing things.",
    "Your future is created by what you do today, not tomorrow.",
    "Success is a series of small wins.",
    "What you do today can improve all your tomorrows.",
    "Success is how high you bounce when you hit bottom.",
    "You are more powerful than you know; you are beautiful just as you are.",
    "Life is short, and it’s up to you to make it sweet.",
    "You must be the change you wish to see in the world.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "The only way to do great work is to love what you do.",
    "Believe in your dreams, no matter how impossible they may seem.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "Success is not just about what you have, but what you give.",
    "You are enough just as you are.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success usually comes to those who are too busy to be looking for it.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Your dreams are valid.",
    "You are the master of your destiny; you can influence, direct and control your own environment.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Life is short, and it’s up to you to make it sweet.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "What you do today can improve all your tomorrows.",
    "Success is a journey, not a destination.",
    "You must do the things you think you cannot do.",
    "Your future is created by what you do today, not tomorrow.",
    "Believe you can and you’re halfway there.",
    "Your life is your message to the world. Make sure it’s inspiring.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Success usually comes to those who are too busy to be looking for it.",
    "You are capable of amazing things.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Life is what happens when you’re busy making other plans.",
    "You are more powerful than you know; you are beautiful just as you are.",
    "Success is a series of small wins.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Believe you can and you’re halfway there.",
    "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.",
    "Success is the key to happiness. Happiness is the key to success.",
    "You must be the change you wish to see in the world.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "Success is how high you bounce when you hit bottom.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.",
    "Success is not for the lazy.",
    "Success is a journey, not a destination.",
    "You are never too old to set another goal or to dream a new dream.",
    "Life is short, and it’s up to you to make it sweet.",
    "You have the power to create your own future.",
    "What you do today can improve all your tomorrows.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Life is what happens when you’re busy making other plans.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Success is not just about what you have, but what you give.",
    "Believe in your dreams, no matter how impossible they may seem.",
    "Your dreams are valid.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Success is how high you bounce when you hit bottom.",
    "You must be the change you wish to see in the world.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Success is the key to happiness. Happiness is the key to success.",
    "You are enough just as you are.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "You are more powerful than you know; you are beautiful just as you are.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Believe you can and you’re halfway there.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "Your life is your message to the world. Make sure it’s inspiring.",
    "Success usually comes to those who are too busy to be looking for it.",
    "You must do the things you think you cannot do.",
    "Success is a journey, not a destination.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Success is the result of preparation, hard work, and learning from failure.",
    "Life is short, and it’s up to you to make it sweet.",
    "You are capable of amazing things.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "What you do today can improve all your tomorrows.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Your dreams are valid.",
    "You are enough just as you are.",
    "Life is what happens when you’re busy making other plans.",
    "Success is not just about what you have, but what you give.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Success usually comes to those who are too busy to be looking for it.",
    "You must be the change you wish to see in the world.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "You are never too old to set another goal or to dream a new dream.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "Believe you can and you’re halfway there.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Success is a journey, not a destination.",
    "Life is short, and it’s up to you to make it sweet.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "Success is how high you bounce when you hit bottom.",
    "Believe in your dreams, no matter how impossible they may seem.",
    "Your dreams are valid.",
    "Success is not for the lazy.",
    "You have the power to create your own future.",
    "Success is a series of small wins.",
    "You are capable of amazing things.",
    "You must be the change you wish to see in the world.",
    "What you do today can improve all your tomorrows.",
    "Your future is created by what you do today, not tomorrow.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Your life is your message to the world. Make sure it’s inspiring.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "Success is not just about what you have, but what you give.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "You are enough just as you are.",
    "What you do today can improve all your tomorrows.",
    "Success is how high you bounce when you hit bottom.",
    "Believe you can and you’re halfway there.",
    "Life is short, and it’s up to you to make it sweet.",
    "Your dreams are valid.",
    "You must do the things you think you cannot do.",
    "Success is a journey, not a destination.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Your future is created by what you do today, not tomorrow.",
    "You have the power to create your own future.",
    "You must be the change you wish to see in the world.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "Believe in your dreams, no matter how impossible they may seem.",
    "Success is a series of small wins.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "You are capable of amazing things.",
    "Your life is your message to the world. Make sure it’s inspiring.",
    "Success is not just what you have, but what you give.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Believe you can and you’re halfway there.",
    "Success is how high you bounce when you hit bottom.",
    "You have the power to create your own future.",
    "Your dreams are valid.",
    "Life is short, and it’s up to you to make it sweet.",
    "Success is not just about what you accomplish in your life, it is about what you inspire others to do.",
    "You are enough just as you are.",
    "Success is a journey, not a destination.",
    "The only way to do great work is to love what you do.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Believe you can and you’re halfway there.",
    "What you do today can improve all your tomorrows.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Success is not just what you have, but what you give.",
    "You must do the things you think you cannot do.",
    "Life is what happens when you’re busy making other plans.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Success is a series of small wins.",
    "You are capable of amazing things.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "You are more powerful than you know; you are beautiful just as you are.",
    "Your dreams are valid.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Success is not just about what you have, but what you give.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "You must be the change you wish to see in the world.",
    "You are enough just as you are.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Success is how high you bounce when you hit bottom.",
    "Life is short, and it’s up to you to make it sweet.",
    "Believe in your dreams, no matter how impossible they may seem.",
    "Your dreams are valid.",
    "Success is a journey, not a destination.",
    "Success usually comes to those who are too busy to be looking for it.",
    "What you do today can improve all your tomorrows.",
    "Success is the key to happiness. Happiness is the key to success.",
    "You have the power to create your own future.",
    "Believe you can and you’re halfway there.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "Success is not just about what you accomplish in your life, it is about what you inspire others to do.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "Your life is your message to the world. Make sure it’s inspiring.",
    "You must do the things you think you cannot do.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Life is short, and it’s up to you to make it sweet.",
    "What you do today can improve all your tomorrows.",
    "You are capable of amazing things.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "Your future is created by what you do today, not tomorrow.",
    "You must be the change you wish to see in the world.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Success is how high you bounce when you hit bottom.",
    "You are enough just as you are.",
    "Your dreams are valid.",
    "Success is a journey, not a destination.",
    "Life is what happens when you’re busy making other plans.",
    "Believe you can and you’re halfway there.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "Success is the key to happiness. Happiness is the key to success.",
    "You have the power to create your own future.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Success is a series of small wins.",
    "Your life is your message to the world. Make sure it’s inspiring.",
    "Success is not just about what you have, but what you give.",
    "Your dreams are valid.",
    "Believe in your dreams, no matter how impossible they may seem.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "You are capable of amazing things.",
    "Life is short, and it’s up to you to make it sweet.",
    "Your future is created by what you do today, not tomorrow.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "What you do today can improve all your tomorrows.",
    "Believe you can and you’re halfway there.",
    "You are enough just as you are.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "You are never too old to set another goal or to dream a new dream.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Success is a journey, not a destination.",
    "Success is how high you bounce when you hit bottom.",
    "You must do the things you think you cannot do.",
    "You must be the change you wish to see in the world.",
    "Success is not just what you accomplish in your life, it is about what you inspire others to do.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    "Success is not just about what you have, but what you give.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "You are more powerful than you know; you are beautiful justas you are.",
    "Life is what happens when you’re busy making other plans."
];

let displayedQuotes = [];
let firstClick = true;

function getRandomQuote() {
    if (displayedQuotes.length === quotes.length) {
        displayedQuotes = [];
    }

    let randomIndex;
    do {
        randomIndex = Math.floor(Math.random() * quotes.length);
    } while (displayedQuotes.includes(randomIndex));

    displayedQuotes.push(randomIndex);
    return quotes[randomIndex];
}

document.getElementById('new-quote').addEventListener('click', function () {
    const quoteElement = document.getElementById('quote');

    if (firstClick) {
        quoteElement.innerHTML = `
            <img src="image.png" alt="Funny Image" style="width: 100%; border-radius: 10px; margin-bottom: 15px;">
            <p>Kupal kaba boss? btw joke lang HAHAHA!</p>
        `;
        firstClick = false;
    } else {
        quoteElement.classList.add('fade-out');

        setTimeout(() => {
            quoteElement.textContent = getRandomQuote();
            quoteElement.classList.remove('fade-out');
            quoteElement.classList.add('fade-in');

            setTimeout(() => {
                quoteElement.classList.remove('fade-in');
            }, 500);
        }, 500);
    }
});
